name: Publish to GitHub Packages

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7

      - name: Build and Publish
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
          GIT_ORGANIZATION_NAME: ${{ secrets.GIT_ORGANIZATION_NAME }}
          GIT_ORGANIZATION_TOKEN: ${{ secrets.GIT_ORGANIZATION_TOKEN }}
          GIT_REPOSITORY_NAME: ${{ secrets.GIT_REPOSITORY_NAME }}
          GIT_REPOSITORY_TOKEN: ${{ secrets.GIT_REPOSITORY_TOKEN }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        run: |
          gradle clean publish --stacktrace
